CREATE TABLE ods_image (
    id INT AUTO_INCREMENT PRIMARY KEY,
    image_blob LONGBLOB NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    coordinates VARCHAR(255) NULL,
    user VARCHAR(255) NOT NULL
);